# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('outstanding', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.CharField(choices=[('CR', 'Creche'), ('PG1', 'Playgroup 1'), ('PG2', 'Playgroup 2'), ('KG1', 'Kindergarten 1'), ('KG2', 'Kindergarten 2'), ('GK', 'Grade K'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5')], default='CR', max_length=2)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('name', models.CharField(max_length=40)),
                ('father_phone', models.CharField(max_length=14)),
                ('mother_phone', models.CharField(max_length=14)),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Student'),
        ),
    ]
