# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
