# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180108_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
