# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20180108_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.AlterField(
            model_name='payment',
            name='outstanding',
            field=models.IntegerField(),
        ),
    ]
