# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20180108_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='outstanding',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
