# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20180111_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='_outstanding',
            field=models.IntegerField(default=0),
        ),
    ]
