# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_payment__outstanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='_outstanding',
            field=models.IntegerField(db_column='Outstanding', default=0),
        ),
    ]
