# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_auto_20180117_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=20),
        ),
    ]
